name: VitalCOre
favicon: null
layout_spectrum: 0.6648219025228173
typography_spectrum: 0.16380701144225895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3594308097381145
  lightness: 0.7415313646197319
  saturation: 0.8241473333910108
  rhythmicContrast: 0.7618465598206967
purpose: []
